[package]
name = "lsbasi-part07"
version = "0.1.0"
authors = ["serg <sergpolkin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
